# Generated by Django 5.2 on 2025-04-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_dailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gfg_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
