# Generated by Django 5.2 on 2025-04-24 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customuser_gfg_username_customuser_leetcode_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDsaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('leetcode', 'LeetCode'), ('gfg', 'GFG')], max_length=50)),
                ('problems_solved', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'source')},
            },
        ),
    ]
