# Generated by Django 5.2 on 2025-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_dailydsaactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
